export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FRANCHISE_PARTNER: 'FRANCHISE_PARTNER',
  SUB_FRANCHISE_PARTNER: 'SUB_FRANCHISE_PARTNER', // Reserved for future phase
};

export const FRANCHISE_TYPES = {
  STATE_FRANCHISE: 'STATE_FRANCHISE',
  DISTRICT_FRANCHISE: 'DISTRICT_FRANCHISE',
  SUB_FRANCHISE: 'SUB_FRANCHISE', // Reserved for future phase
};

export const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
};

export const OTP_PURPOSE = {
  PARTNER_LOGIN: 'PARTNER_LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
};

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
};
