export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  STATE_FRANCHISE: 'STATE_FRANCHISE',
  DISTRICT_FRANCHISE: 'DISTRICT_FRANCHISE',
  SUB_FRANCHISE: 'SUB_FRANCHISE',
  FRANCHISE_PARTNER: 'FRANCHISE_PARTNER',
};

export const FRANCHISE_TYPES = {
  STATE_FRANCHISE: 'STATE_FRANCHISE',
  DISTRICT_FRANCHISE: 'DISTRICT_FRANCHISE',
  SUB_FRANCHISE: 'SUB_FRANCHISE',
  NON_EXCLUSIVE_DISTRICT: 'NON_EXCLUSIVE_DISTRICT',
  STANDARD_EXCLUSIVE_DISTRICT: 'STANDARD_EXCLUSIVE_DISTRICT',
  PREMIUM_EXCLUSIVE_DISTRICT: 'PREMIUM_EXCLUSIVE_DISTRICT',
};

export const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
};

export const OTP_PURPOSE = {
  PARTNER_LOGIN: 'PARTNER_LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CUSTOMER_CONFIRMATION: 'CUSTOMER_CONFIRMATION',
  PARTNER_REGISTRATION: 'PARTNER_REGISTRATION',
};

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
};

export const CUSTOMER_TYPES = {
  RESIDENTIAL: 'RESIDENTIAL',
  COMMERCIAL: 'COMMERCIAL',
  INDUSTRIAL: 'INDUSTRIAL',
};

export const ELECTRICITY_PHASES = {
  SINGLE_PHASE: 'SINGLE_PHASE',
  THREE_PHASE: 'THREE_PHASE',
};

export const CONFIRMATION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
};

export const CONFIRMATION_METHODS = {
  OTP: 'OTP',
  SIGNATURE: 'SIGNATURE',
  MANUAL: 'MANUAL',
};

export const INSTALLATION_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  FLAGGED: 'FLAGGED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const LOCATION_VERIFICATION_STATUS = {
  PENDING_GPS: 'PENDING_GPS',
  GPS_CAPTURED: 'GPS_CAPTURED',
  VERIFIED: 'VERIFIED',
  LOW_ACCURACY: 'LOW_ACCURACY',
  TERRITORY_MISMATCH: 'TERRITORY_MISMATCH',
  GEOCODING_FAILED: 'GEOCODING_FAILED',
  LOCATION_PERMISSION_DENIED: 'LOCATION_PERMISSION_DENIED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  REJECTED: 'REJECTED',
  ADMIN_OVERRIDDEN: 'ADMIN_OVERRIDDEN',
};

export const GPS_ACCURACY_STATUS = {
  GOOD: 'GOOD',
  ACCEPTABLE: 'ACCEPTABLE',
  POOR: 'POOR',
};


export const CARD_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  PENDING_TRANSFER: 'PENDING_TRANSFER',
  TRANSFERRED: 'TRANSFERRED',
  INSTALLED: 'INSTALLED',
  BLOCKED: 'BLOCKED',
};

export const CARD_OWNER_TYPES = {
  HEADQUARTERS: 'HEADQUARTERS',
  FRANCHISE_PARTNER: 'FRANCHISE_PARTNER',
};

export const CARD_ACTIONS = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  TRANSFER_INITIATED: 'TRANSFER_INITIATED',
  TRANSFER_CONFIRMED: 'TRANSFER_CONFIRMED',
  TRANSFER_DISPUTED: 'TRANSFER_DISPUTED',
  TRANSFER_CANCELLED: 'TRANSFER_CANCELLED',
  TRANSFERRED: 'TRANSFERRED',
  INSTALLED: 'INSTALLED',
  BLOCKED: 'BLOCKED',
  UNBLOCKED: 'UNBLOCKED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  CORRECTION: 'CORRECTION',
};

export const TRANSACTION_TYPES = {
  SALE: 'SALE',
  TRANSFER: 'TRANSFER',
  COMPLIMENTARY: 'COMPLIMENTARY',
};

export const TRANSACTION_STATUS = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const DISPUTE_REASONS = {
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  INCORRECT_PRICE: 'INCORRECT_PRICE',
  WRONG_SERIALS: 'WRONG_SERIALS',
  CARDS_NOT_RECEIVED: 'CARDS_NOT_RECEIVED',
  DAMAGED_CARDS: 'DAMAGED_CARDS',
  OTHER: 'OTHER',
};

export const NOTIFICATION_TYPES = {
  PARTNER_ACCOUNT_CREATED: 'PARTNER_ACCOUNT_CREATED',
  PARTNER_ACTIVATED: 'PARTNER_ACTIVATED',
  PARTNER_SUSPENDED: 'PARTNER_SUSPENDED',
  PARTNER_DEACTIVATED: 'PARTNER_DEACTIVATED',
  CARD_RECEIVED: 'CARD_RECEIVED',
  CARD_TRANSFER_PENDING: 'CARD_TRANSFER_PENDING',
  CARD_TRANSFER_CONFIRMED: 'CARD_TRANSFER_CONFIRMED',
  CARD_TRANSFER_DISPUTED: 'CARD_TRANSFER_DISPUTED',
  CUSTOMER_ADDED: 'CUSTOMER_ADDED',
  INSTALLATION_SUBMITTED: 'INSTALLATION_SUBMITTED',
  INSTALLATION_VERIFIED: 'INSTALLATION_VERIFIED',
  INSTALLATION_REVIEW_REQUIRED: 'INSTALLATION_REVIEW_REQUIRED',
  INSTALLATION_REJECTED: 'INSTALLATION_REJECTED',
  TERRITORY_MISMATCH: 'TERRITORY_MISMATCH',
  PAYMENT_SUBMITTED: 'PAYMENT_SUBMITTED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  IMPORTANT_ADMIN_ALERT: 'IMPORTANT_ADMIN_ALERT',
};

export const ENTITY_TYPES = {
  PARTNER: 'PARTNER',
  CARD: 'CARD',
  TRANSACTION: 'TRANSACTION',
  CUSTOMER: 'CUSTOMER',
  INSTALLATION: 'INSTALLATION',
  LOCATION_VERIFICATION: 'LOCATION_VERIFICATION',
  USER: 'USER',
  SYSTEM: 'SYSTEM',
};

export const AUDIT_ACTIONS = {
  // Auth
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  PARTNER_LOGIN: 'PARTNER_LOGIN',
  PASSWORD_RESET: 'PASSWORD_RESET',
  // Partner
  PARTNER_CREATED: 'PARTNER_CREATED',
  PARTNER_UPDATED: 'PARTNER_UPDATED',
  PARTNER_STATUS_CHANGED: 'PARTNER_STATUS_CHANGED',
  REGISTRATION_OTP_GENERATED: 'REGISTRATION_OTP_GENERATED',
  REGISTRATION_SMS_SENT: 'REGISTRATION_SMS_SENT',
  REGISTRATION_SMS_FAILED: 'REGISTRATION_SMS_FAILED',
  REGISTRATION_EMAIL_SENT: 'REGISTRATION_EMAIL_SENT',
  REGISTRATION_EMAIL_FAILED: 'REGISTRATION_EMAIL_FAILED',
  // Card
  CARD_CREATED: 'CARD_CREATED',
  CARD_ASSIGNED: 'CARD_ASSIGNED',
  CARD_TRANSFERRED: 'CARD_TRANSFERRED',
  CARD_INSTALLED: 'CARD_INSTALLED',
  CARD_BLOCKED: 'CARD_BLOCKED',
  CARD_UNBLOCKED: 'CARD_UNBLOCKED',
  // Transaction
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_CONFIRMED: 'TRANSACTION_CONFIRMED',
  TRANSACTION_DISPUTED: 'TRANSACTION_DISPUTED',
  TRANSACTION_CANCELLED: 'TRANSACTION_CANCELLED',
  // Payment
  PAYMENT_SUBMITTED: 'PAYMENT_SUBMITTED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  // Customer & Installation
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  INSTALLATION_CREATED: 'INSTALLATION_CREATED',
  INSTALLATION_CONFIRMED: 'INSTALLATION_CONFIRMED',
  INSTALLATION_VERIFIED: 'INSTALLATION_VERIFIED',
  INSTALLATION_REJECTED: 'INSTALLATION_REJECTED',
  // GPS & Territory
  GPS_CAPTURED: 'GPS_CAPTURED',
  TERRITORY_MISMATCH_DETECTED: 'TERRITORY_MISMATCH_DETECTED',
  ADMIN_LOCATION_OVERRIDE: 'ADMIN_LOCATION_OVERRIDE',
};


